Added aggregation pipeline operators
LucasSGomide/MongoDB pull request #4
Opened 2021-01-25 20:17 UTC by phelipe-ohlsen

Referente ao 25.1: Aggregation Pipeline
- [x] `$match`
- [x] `$limit`
- [ ] `$lookup`
- [x] `$group`
- [x] `$unwind`
- [x] `$project`

Observações:
 1- O `$lookup` ainda não está pronto, mas já está no documento.
 2- Adicionei linhas para separar os operadores nas sessão do Aggregation Pipeline. Caso julguem ser uma boa implementação, podíamos colocar nas outras sessões também.
3- O sumário não está atualizado com as novas sessões.

2021-01-25 22:15 UTC, cleytonoliveira requested changes

2021-01-25 22:15 UTC, cleytonoliveira commented on README.md
> +### $match
```suggestion
### $MATCH
```

2021-01-25 22:15 UTC, cleytonoliveira commented on README.md
> +### $limit
```suggestion
### $LIMIT
```

2021-01-25 22:15 UTC, cleytonoliveira commented on README.md
> +````javasc
```suggestion
````javascript
```

2021-01-25 22:15 UTC, cleytonoliveira commented on README.md
> +### $lookup
```suggestion
### $LOOKUP
```

2021-01-25 22:15 UTC, cleytonoliveira commented on README.md
> +### $group
```suggestion
### $GROUP
```

2021-01-25 22:15 UTC, cleytonoliveira commented on README.md
> +````javas
```suggestion
````javascript
```

2021-01-25 22:15 UTC, cleytonoliveira commented on README.md
> +````javas
```suggestion
````javascript
```

2021-01-25 22:15 UTC, cleytonoliveira commented on README.md
> +### $unwind
```suggestion
### $UNWIND
```

2021-01-25 22:15 UTC, cleytonoliveira commented on README.md
> +### $project
```suggestion
### $PROJECT
```

2021-01-26 15:19 UTC, isabellavjs requested changes
Ficou top @phelipe-ohlsen ! Deixei algumas sugestões e peguei uns typos pra corrigir. Mais tarde eu contribuo tbm pras sessões que faltam!

2021-01-26 15:19 UTC, isabellavjs commented on README.md
> +The aggregation pipeline is a framework for MongoDB. Documents enter a multi-stage pipeline that transforms the documents into an aggregated result. Each stage transforms the documents as they pass f
```suggestion
The aggregation pipeline is a framework for MongoDB. Documents enter a multi-stage pipeline that transforms the documents into an aggregated result. Documents pass through the stages in sequence. Each stage transforms the documents as they pass from one stage to another. 
```

2021-01-26 15:19 UTC, isabellavjs commented on README.md
> +Limits the number of documents passed to the next stage in the pipeline.
```suggestion
Passes only the first n documents to the next stage in the pipeline, in which n is the specified positive integer.
```

2021-01-26 15:19 UTC, isabellavjs commented on README.md
> +Returns five results that matches the specified condition from the previous stage.
```suggestion
Returns the first five results that matches the specified condition from the previous stage.
```

2021-01-26 15:19 UTC, isabellavjs commented on README.md
> +The `<field>` may be named as you see fit, howerver, the `<accumulator>` must be a accumulator operator.
```suggestion
The `<field>` may be named as you see fit, however, the `<accumulator>` must be an accumulator operator.
```

2021-01-26 15:19 UTC, isabellavjs commented on README.md
> +This operator groups documents by the specified `_id` expression. It's worth mentioning that the specified `_id` is actually a "parameter" of `$group` and is not to be mistaken with `_id` from the co
```suggestion
This operator groups documents by the specified `_id` expression. It's worth mentioning that the specified `_id` is actually a "parameter" of `$group` and is not to be mistaken with `_id` from the collections. The operator `_id` is required. If you specify a value of `null` the $group stage calculates accumulated values for the input document as a whole.
```

2021-01-26 15:19 UTC, isabellavjs commented on README.md
> +**OBS:** If you set `_id` as `null`, you will group all documents.
```suggestion
```

2021-01-26 15:19 UTC, isabellavjs commented on README.md
> +If we were to apply the `$unwind` operator:
```suggestion
If we apply the `$unwind` operator:
```

2021-01-26 23:18 UTC, merged